In [1]:
import ulmo
#from ulmo import cdec
from ulmo.util import convert_datetime

import os
import shutil
import sys
import pandas as pd
import numpy as np
import plotly.express as px
import time
from datetime import datetime

In [2]:
outer_dir = os.path.abspath(os.path.join(os.getcwd() ,"../.."))
unimpath = os.path.join(outer_dir, "IFT_files", 'Unimpaired Flow')
nav_div_csv = os.path.join(outer_dir, "IFT_files", 'Indian','Navarro_estimated_diversions.csv')


LOI_name = "Sproul" #Sproul or Indian 
if LOI_name == "Sproul":
    site_code = '11476600' # Bull Creek gage https://waterdata.usgs.gov/nwis/inventory/?site_no=11476600&agency_cd=USGS
elif LOI_name == "Indian":
    site_code = '11468000' # Navarro Gage https://waterdata.usgs.gov/nwis/inventory/?site_no=11468000&agency_cd=USGS
else:
    print("LOI not recognized")

In [86]:
def download_daily_gage_data(gage_id):
    """Function to download stream gage data from USGS API"""
    result = ulmo.usgs.nwis.get_site_data(site_code=gage_id, 
                                          service='dv',
                                          parameter_code='00060',
                                          methods='all',
                                          start = '1850-1-1',
                                          end = '2021-9-30'
                                         )
    if result == {}:
        result = ulmo.usgs.nwis.get_site_data(site_code=str(site_code), 
                                              service='dv',
                                              parameter_code='72137',
                                              methods='all',
                                              start = '1850-1-1',
                                              end = '2021-9-30'
                                             )
        if result == {}:
            print("discharge parameters not available for this gage")
            return

    first_key = list(result.keys())[0]
    # Convert to dataframe
    first_key = list(result.keys())[0]
    df = pd.DataFrame.from_dict(result[first_key]['values'])
    df["value"] = df["value"].replace(['---','BRT','ART','-1', 'nan'],np.NaN)
    df[['value']] = df[['value']].apply(pd.to_numeric)
    df['datetime'] =  pd.to_datetime(df['datetime'])
    df['gage_id'] =  gage_id
    return df

In [87]:
def evaluate_record(df):
    """Evaluate the gage data completeness"""
    first = df['datetime'].min()
    last = df['datetime'].max()
    Qmin = df['value'].min()
    Qmax = df['value'].max()
    delta = last - first
    all_records = len(df)
    df_valid = df.dropna(subset=['value'])
    valid_records = len(df_valid)
    pct_missing = all_records / valid_records
    pct_valid = valid_records / delta.days
    print('First date: {}'.format(first))
    print('Last date: {}'.format(last))
    print('Min Flow: {} cfs'.format(Qmin))
    print('Max Flow: {} cfs'.format(Qmax))
    print('Percent of records with missing data: {0:.1%}'.format(1 - pct_missing))
    print('Percent of the timeframe with valid records: {0:.1%}'.format(pct_valid))
    df_month = df_valid.resample('M', on='datetime').count()
    df_month = df_month['value'].reset_index()
    df_month.rename(columns={'value': 'valid_count'}, inplace=True)
    #Remove months with zero days
    df_month = df_month.loc[df_month.valid_count > 0]
    df_month['days_in_month'] = df_month['datetime'].dt.daysinmonth
    df_month['pct_valid_in_month'] = df_month['valid_count'] / df_month['days_in_month']
    pct_partial_month = len(df_month.loc[df_month['pct_valid_in_month'] < 1]) / len(df_month)
    print('Percent of partial months: {0:.1%}'.format(pct_partial_month))
    
    
    #Evaluation the number in days in each month
    df_day_freq = (df_month.groupby('valid_count')
               .agg({'days_in_month':'count'})
               .reset_index()
               .rename(columns={'days_in_month':'Count_months'})
              )
    print('Number of unique day counts per month: {}'.format(len(df_day_freq)))
    return df_day_freq

In [88]:
df = download_daily_gage_data(str(site_code))
df_eval = evaluate_record(df)

processing data from request: https://waterservices.usgs.gov/nwis/dv/?site=11476600&endDT=2021-09-30&startDT=1850-01-01&format=waterml&parameterCd=00060

First date: 1960-10-01 00:00:00
Last date: 2021-09-30 00:00:00
Min Flow: 0.02 cfs
Max Flow: 4900.0 cfs
Percent of records with missing data: 0.0%
Percent of the timeframe with valid records: 97.8%
Percent of partial months: 0.4%
Number of unique day counts per month: 5

In [89]:
# Add in month and day fields
df['Year'] = df.datetime.dt.year
df['Month'] = df.datetime.dt.month
df['Day'] = df.datetime.dt.day

#Add in water year
def assign_wy(row):
    if row.datetime.month>=10:
        return(pd.datetime(row.datetime.year+1,1,1).year)
    else:
        return(pd.datetime(row.datetime.year,1,1).year)

df['Water Year'] = df.apply(lambda x: assign_wy(x), axis=1)

In [90]:
# Check for complete years
df_year = (df.groupby(['gage_id', 'Water Year'])
           .agg({'value':'mean', 'datetime':'count'})
           .reset_index()
           .rename(columns={'value':'avg_ann_flow', 'datetime':'days_with_data'})
          )
df_year.sort_values(by=['days_with_data', 'Water Year'], ascending=[True, True])

     gage_id  Water Year  days_with_data  avg_ann_flow
58  11476600        2019              30      1.173333
59  11476600        2020             216     22.647731
60  11476600        2021             362     51.815331
0   11476600        1961             365    124.199452
1   11476600        1962             365     77.458904
2   11476600        1963             365    175.044932
4   11476600        1965             365    119.557534
5   11476600        1966             365    101.396164
6   11476600        1967             365    137.122192
8   11476600        1969             365    187.930137
9   11476600        1970             365    141.369288
10  11476600        1971             365    129.711753
12  11476600        1973             365     98.996986
13  11476600        1974             365    249.239644
14  11476600        1975             365    129.327781
16  11476600        1977             365      9.717452
17  11476600        1978             365    215.926027
18  11476600        1979             365     54.818904
20  11476600        1981             365     73.134767
21  11476600        1982             365    203.705479
22  11476600        1983             365    286.541918
24  11476600        1985             365     80.299589
25  11476600        1986             365    156.406219
26  11476600        1987             365     73.730849
28  11476600        1989             365     86.252219
29  11476600        1990             365     52.403836
30  11476600        1991             365     39.094521
32  11476600        1993             365    114.193671
33  11476600        1994             365     54.666411
34  11476600        1995             365    179.263370
..       ...         ...             ...           ...
37  11476600        1998             365    174.597808
38  11476600        1999             365    127.411753
40  11476600        2001             365     44.798356
41  11476600        2002             365    105.679562
42  11476600        2003             365    148.587205
44  11476600        2005             365    101.250137
45  11476600        2006             365    191.883836
46  11476600        2007             365     78.167014
48  11476600        2009             365     61.249616
49  11476600        2010             365    116.687342
50  11476600        2011             365    124.362603
52  11476600        2013             365     87.448959
53  11476600        2014             365     22.520658
54  11476600        2015             365     81.453918
56  11476600        2017             365    189.835014
57  11476600        2018             365     62.228384
3   11476600        1964             366     81.156011
7   11476600        1968             366    114.929781
11  11476600        1972             366    102.894536
15  11476600        1976             366     75.761749
19  11476600        1980             366    128.729262
23  11476600        1984             366    150.210383
27  11476600        1988             366     64.285273
31  11476600        1992             366     48.566421
35  11476600        1996             366    128.317486
39  11476600        2000             366    109.387978
43  11476600        2004             366    109.756721
47  11476600        2008             366     82.230246
51  11476600        2012             366     75.633115
55  11476600        2016             366    110.387432

[61 rows x 4 columns]

In [91]:
# Calculate the unimpaired flow  
if LOI_name == "Sproul":
    # formula from "d:\Users\kklausmeyer\Documents\workspace\freshwater\IFT_files\SF_Sproul\Sproul Hydrographs fr Bull Creek v1.xlsm"
    df['flow'] = (np.where(df['value']<2.706, 0.218*df['value']**2-0.0144*df['value'], df['value']*0.739))/24 * 5
    df['flow'] = np.where(df['flow']<0, 0, df['flow'])
elif LOI_name == "Indian":
    DApod = 39 #sqmiles
    DAgage = 303
    Ppod = 40.4 # inches from PRISM
    Pgage = 40
    factor = (DApod/ DAgage) * (Ppod/ Pgage)
    df_nav = pd.read_csv(nav_div_csv)
    df_nav = df_nav.drop(['Month'], axis=1)
    df1 = pd.merge(df, df_nav[['Month.1', 'Daily cfs']], left_on='Month', right_on="Month.1", how='left')
    df1["nav_unimpaired"] = df1['value'] + df1['Daily cfs']
    #Calc Indian Creek unimpaired
    df1['flow'] = df1["nav_unimpaired"] * factor
    df = df1.drop(['Month.1', "nav_unimpaired", 'Daily cfs'], axis=1)
    

else:
    print("LOI not recognized")

In [92]:
# Export data
df.rename(columns={'datetime': 'DTTM'}, inplace=True)
df.drop(['qualifiers', 'value', 'gage_id'], axis=1, inplace=True)
file_out = os.path.join(unimpath, LOI_name + ".csv")
df.to_csv(file_out, encoding='utf-8', index=False)